
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://hiraksarkar.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: ""

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Hirak Sarkar"
title: "{ Hirak Sarkar }"
description: "Personal profile, my web home"
keywords: "sarkar, hirak, compbio, bioinformatics, RNA-seq"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"

background-img: "../img/back61.jpeg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: False # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
linkedin_url: "https://linkedin.com/in/hiraksarkar"
new_color: "color: #e34f26;"

lines: # You can add HTML Tags in the Text
  - text: "Hi, this is Hirak"

- text: "<span {{ site.new_color }}><u>[NEW]</u>
</span>I joined Facebook as a data scientist intern and working on deep learning based workflows for disaster tracking"

  #- text: "<span {{ site.new_color }}><u>[NEW]</u>
  #</span>I am Actively looking for research internships<sup>
  #[<a href={{ site.linkedin_url }}>
  #<i class=\"fa fa-linkedin\"></i></a>]</sup> in Data Analysis, Applied
  #ML and Bioinformatics."
  #- text: "internships<sup>[<a href="https://linkedin.com/in/hiraksarkar"><i class="fa fa-linkedin"></i></a>]</sup>
#in Data Analysis, Applied ML and Bioinformatics."
  #- text: "Welcome to my web home"

me-img: "/img/profile.jpg"

# To use facebook profile pic comment the previous line and uncomment the following
# line, and replace 'user_id' with your facebook user id.
# Facebook user id can be found by clicking on your profile pic and the large number
# in the end of the url just before '&type' is your user id.
# Note: fbid is not the same as user id and user id only contains numbers

# me-img: "https://graph.facebook.com/user_id/picture?type=large&width=500&height=500"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

# me-img: "https://github.com/user_name.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: False
fb-share: False
twitter-share: True
linkedin-share: True
reddit-share: False
google-plus-share: False
tumblr-share: False
pinterest-share: False
pocket-share: False
vkontakte-share: False

disqus-shortname: "panossakkos"

syntax-highlight: True


############
# Timeline #
############

events:
  - image: "/img/back_img_net.jpg"
    date: "June 2018 - Present"
    description: "Rediscovering myself in San Fransisco"


  - image: "/img/back_img_net.jpg"
    date: "June 2017 - Present"
    description: "Beside working on a cool data structures for [*pufferfish*](https://github.com/COMBINE-lab/pufferfish), de-Bruijn graph
based mappers, I got really interested in publicly available big data. With Rob, I am now figuring out this maze of
[Sequence Read Archive](https://www.ncbi.nlm.nih.gov/sra), and trying to find meaningful insights from this exponentially increasing public database.
Keep checking for exciting upcoming news. Released [[biorXiv]](https://doi.org/10.1101/191874)."


  - image: "/img/back_img_net.jpg"
    date: "March 2017 - May 2017"
    description: "We worked on a new way for solving the abundance calculation problem for RNA-seq read mapping.
    Kallisto and RapMap are not as accurate as you think in special cases, such as discussed
    [here](https://cgatoxford.wordpress.com/2016/08/17/why-you-should-stop-using-featurecounts-htseq-or-cufflinks2-and-start-using-kallisto-salmon-or-sailfish/).
    We propose Selective Alignment. Preprinted [[biorXiv]](https://doi.org/10.1101/138800)."

  - image: "/img/back_img_net.jpg"
    date: "Oct 2016 - Feb 2017"
    description: "We worked on RNA-seq compression algorithm. Developed a state-of-the-art RNA-seq compression tool,
    introducing the idea of semi-reference based compression, now published in [*Bioinformatics*](https://doi.org/10.1093/bioinformatics/btx428) now. I also worked on a poster
    with [Prof Siepel](http://siepellab.labsites.cshl.edu/), presented in [*BioData*](https://meetings.cshl.edu/meetings.aspx?meet=DATA&year=16)."

  - image: "/img/back_img_net.jpg"
    date: "May 2016 - July 2016"
    description: "I collaborated with [Prof. Adam Siepel](http://siepellab.labsites.cshl.edu/). Learned a lot about probabilistic
    graphical model. Developed a model for incorporating information from GRO-seq data and RNA-seq data.
    Such multimodal analysis has not been explored before."

  - image: "/img/back_img_net.jpg"
    date: "May 2016"
    description: "Yayy, I passed my Research Proficiency Examination [[slides]](https://docs.google.com/viewer?url=https://raw.githubusercontent.com/hiraksarkar/hiraksarkar.github.io/master/data/RPE_slides.pdf). Honored to have [*Prof Mike Schatz*](http://schatz-lab.org/)(JHU),
    [*Prof Adam Siepel*](http://siepellab.labsites.cshl.edu/)(CSHL) and my supervisor Prof. Robert Patro on my committee."

  - image: "/img/timeline/combine_lab_logo.png"
    date: "May 2015 - May 2016"
    description: "I started working with [*Prof Robert Patro*](http://www.robpatro.com/redesign/), excited, at the end of almost an year we (with my other labmates) developed two
    tools, [*RapMap*](https://github.com/COMBINE-lab/RapMap/) and [*RapClust*](https://github.com/COMBINE-lab/RapClust)."

  - image: "/img/timeline/sbu3.png"
    date: "Aug 2014 - May 2015"
    description: "I joined Stony Brook University and recieved presitigious CS Chair Fellowship of 10,000$.
    I met my supervisor Rob Patro and cleared all 5 qualifier courses :)."



# First image of the Timeline

timeline-img: "./img/profile.jpg"

###########
# Contact #
###########

email: "contact@hiraksarkar.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "John Smith is an awesome person. He lives in Flatland, where he works on two-dimensional engineering projects. In his spare time, John likes to eat cotton candy."
author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

social:
  - title: "linkedin"
    url: "https://linkedin.com/in/hiraksarkar"
  - title: "twitter"
    url: "https://twitter.com/hrksrkr"
  - title: "github"
    url: "https://github.com/hiraksarkar"

#  - title: "scholar"
#    url: "https://scholar.google.com"

############
# 404 page #
############

err-404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

keybase-username: johnsmith
keybase-in-social: False
keybase-in-footer: False

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  #Blog: 'latest-post'
  About: 'realabout'
  Bio: 'bio'
  Publication: 'publication'
  Events: 'research'
  Contact: 'contact'

#theme: "https://github.com/le4ker/personal-jekyll-theme"

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
